###########################################################################################################################################################################################################################
#                                                                                                                                                                                                                         #
#                                                          SCRIPT CAMBIO NOME VMC HELTY FLOW PLUS RELEASE [VER. 1.0]                                                                                                      #
#                                                                                                                                                                                                                         #
# SVILUPPATO DA ING. DANILO ROBOTTI, ALLE PRIME ARMI CON HOME ASSISTANT :)                                                                                                                                                #
#                                                                                                                                                                                                                         #
# LICENZA D'USO – USO PERSONALE NON COMMERCIALE                                                                                                                                                                           #
#                                                                                                                                                                                                                         #
# COPYRIGHT © ING. DANILO ROBOTTI                                                                                                                                                                                         #
#                                                                                                                                                                                                                         #
# TUTTI I DIRITTI RISERVATI.                                                                                                                                                                                              #
#                                                                                                                                                                                                                         #
# QUESTA LICENZA SI APPLICA A TUTTE LE VERSIONI DEL PRESENTE SOFTWARE CHE INCLUDE I SEGUENTI FILES:                                                                                                                       #
#   - VMC_CLONA.YAML                                                                                                                                                                                                      #
#   - VMC_CLONA_SCHEDA_MANUALE_INTERFACCIA.TXT                                                                                                                                                                            #
#   - VMC_MASTER.YAML                                                                                                                                                                                                     #
#   - VMC_MASTER_AUTOMAZIONE.TXT                                                                                                                                                                                          #
#   - VMC_MASTER_SCHEDA_MANUALE_INTERFACCIA.TXT                                                                                                                                                                           #
#   - VMC_MASTER_SCRIPT_CAMBIO_IP.SH                                                                                                                                                                                      #
#   - VMC_MASTER_SCRIPT_CAMBIO_NOME.SH                                                                                                                                                                                    #
#   - VMC_SCRIPT_CLONA.SH                                                                                                                                                                                                 #
# A PARTIRE DALLA PRIMA VERSIONE PUBBLICATA E SUCCESSIVE                                                                                                                                                                  #
#                                                                                                                                                                                                                         #
# È CONCESSO:                                                                                                                                                                                                             #
#  - L'UTILIZZO DEL SOFTWARE ESCLUSIVAMENTE PER FINI PERSONALI E NON COMMERCIALI                                                                                                                                          #
#  - LA DISTRIBUZIONE LIBERA, PURCHÉ VENGA MANTENUTO IL PRESENTE TESTO DI LICENZA E SIA RISPETTATO IL DIVIETO D'USO COMMERCIALE                                                                                           #
#                                                                                                                                                                                                                         #
# QUALSIASI USO NON AUTORIZZATO AD USO COMMERCIALE COSTITUISCE VIOLAZIONE DEL DIRITTO D'AUTORE E POTRÀ ESSERE PERSEGUITO LEGALMENTE                                                                                       #
#                                                                                                                                                                                                                         #
# PER RICHIESTE DI LICENZA COMMERCIALE O USI PARTICOLARI, CONTATTARE L’AUTORE: danilo.robotti@gmail.com                                                                                                                   #
#                                                                                                                                                                                                                         #
# VERSIONE LICENZA: 1.0                                                                                                                                                                                                   #
# DATA: 30 APRILE 2025                                                                                                                                                                                                    #
#                                                                                                                                                                                                                         #
# Esonero di Responsabilità                                                                                                                                                                                               #
# In nessun caso lo sviluppatore sarà responsabile di danneggiamenti diretti, indiretti o conseguenti, correlati a difetti del presente software                                                                          #
# L’usufruitore ha l’onere e la responsabilità della scelta, dell’installazione, dell’uso e della gestione del software al fine del raggiungimento del risultato prefissatosi                                             #
#                                                                                                                                                                                                                         #
###########################################################################################################################################################################################################################
#!/bin/bash
echo "VMNM $1" | nc 999.999.999.999 5001