###########################################################################################################################################################################################################################
#                                                                                                                                                                                                                         #
#                                                          CLONA VMC HELTY FLOW PLUS RELEASE [V1.0.0]                                                                                                                     #
# SVILUPPATO DA DANILO ROBOTTI, ALLE PRIME ARMI CON HOME ASSISTANT                                                                                                                                                        #
# SI INVITA A DIVULGARE IL CODICE PER RENDERLO SEMPRE PIU' EFFICACIE ED EFFICIENTE, ANCHE AL SOTTOSCRITTO! :)                                                                                                             #
# EMAIL: danilo.robotti@gmail.com                                                                                                                                                                                         #
#                                                                                                                                                                                                                         #
###########################################################################################################################################################################################################################
sensor:
- platform: template
  sensors:
    vmc_master_slave_verifica_nome_inserito:                                    # [CONFIGURAZIONE PIU' RICHIAMI] [AUTOMAZIONE 0 RICHIAMI] [INTERFACCIA PIU' RICHIAMI]
      friendly_name: "Verifica Nome"
      value_template: >
        {% if states.input_text.vmc_master_slave_nome_insert.state | regex_match('^[a-z]{1,10}$') and
              states.input_text.vmc_master_slave_nome_insert.state | replace(' ', '') == states.input_text.vmc_master_slave_nome_insert.state and
              states.input_text.vmc_master_slave_nome_insert.state | lower != 'master'and
              states.input_text.vmc_master_slave_nome_insert.state | lower != 'clona' %}
          ok
        {% else %}
          not ok
        {% endif %}
      icon_template: mdi:check-circle

    vmc_master_slave_verifica_ip_inserito:                                      # [CONFIGURAZIONE PIU' RICHIAMI] [AUTOMAZIONE 0 RICHIAMI] [INTERFACCIA PIU' RICHIAMI]
      friendly_name: "Verifica IP"
      value_template: >
        {% if states.input_text.vmc_master_slave_ip_insert.state is match("^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$") %}
          {{ states.input_text.vmc_master_slave_ip_insert.state }}
        {% else %}
          not ok
        {% endif %}
      icon_template: mdi:ip 

input_text:
  vmc_master_slave_nome_insert:                                                 # [CONFIGURAZIONE PIU' RICHIAMI] [AUTOMAZIONE 0 RICHIAMI] [INTERFACCIA PIU' RICHIAMI]
    name: Nome nuova VMC
    initial: ""
    min: 0
    max: 10

  vmc_master_slave_ip_insert:                                                   # [CONFIGURAZIONE PIU' RICHIAMI] [AUTOMAZIONE 0 RICHIAMI] [INTERFACCIA PIU' RICHIAMI]
    name: IP nuova VMC su Porta 5001
    initial: ""

input_boolean: 
  vmc_master_slave_check_avvio_clonazione:                                      # [CONFIGURAZIONE 0 RICHIAMI] [AUTOMAZIONE 0 RICHIAMI] [INTERFACCIA, PIU' RICHIAMI]
    name: Mostra/Nascondi Clona VMC
    initial: false
    icon: mdi:cog
    
  vmc_master_slave_check_avvio_script_vmc_master_slave_duplica_vmc:             # [CONFIGURAZIONE PIU' RICHIAMI] [AUTOMAZIONE 0 RICHIAMI] [INTERFACCIA, PIU' RICHIAMI]
    name: Check Avvio Scipt Clonazione VMC
    initial: false
    icon: mdi:check-circle

shell_command:                                                                  # [CONFIGURAZIONE PIU' RICHIAMI] [AUTOMAZIONE 0 RICHIAMI] [INTERFACCIA 0 RICHIAMI]
  vmc_master_slave_rimuovi_caratteri_di_ritorno: find /config/packages/vmc_helty_flow/master -type f -name "*.sh" -exec sed -i 's/\r$//' {} \; # TROVA E RIMUOVE CARATTERI DI RITORNO IN TUTTI I FILES *.sh CONTENUTI NELLA CARTELLA
  vmc_master_slave_clona:                        bash /config/packages/vmc_helty_flow/master/vmc_script_clona.sh {{ states('input_text.vmc_master_slave_nome_insert') }} {{ states('input_text.vmc_master_slave_ip_insert') }}

script:
  vmc_master_slave_duplica_vmc:                                                 # [CONFIGURAZIONE 0 RICHIAMI] [AUTOMAZIONE 0 RICHIAMI] [INTERFACCIA, PIU' RICHIAMI]
    alias: Avvio Clona VMC
    sequence:
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ is_state('sensor.vmc_master_slave_verifica_nome_inserito', 'ok') }}"
          - condition: template
            value_template: "{{ not is_state('sensor.vmc_master_slave_verifica_ip_inserito', 'not ok') }}"
      - service: shell_command.vmc_master_slave_rimuovi_caratteri_di_ritorno
      - service: shell_command.vmc_master_slave_clona
      - service: input_boolean.turn_on
        entity_id: input_boolean.vmc_master_slave_check_avvio_script_vmc_master_slave_duplica_vmc
    icon: mdi:cursor-pointer

  vmc_master_slave_restart_ha:                                                  # [CONFIGURAZIONE 0 RICHIAMI] [AUTOMAZIONE 0 RICHIAMI] [INTERFACCIA, PIU' RICHIAMI]
    alias: E' necessario riavviare H.A. per rendere effettive le modifiche!
    sequence:
      - service: input_text.set_value
        target:
          entity_id:
            - input_text.vmc_master_slave_nome_insert
            - input_text.vmc_master_slave_ip_insert
        data:
          value: ''
      - service: input_boolean.turn_off
        entity_id: input_boolean.vmc_master_slave_check_avvio_script_vmc_master_slave_duplica_vmc
      - service: homeassistant.restart
    icon: mdi:home-assistant